import { describe, it, expect, vi } from 'vitest'

const mockSingle = vi.fn()

vi.mock('@/lib/supabase/admin', () => ({
  supabaseAdmin: {
    from: vi.fn(() => ({
      select: vi.fn(() => ({
        eq: vi.fn(() => ({ single: mockSingle })),
      })),
    })),
  },
}))

import { GET } from './route'

const CHATBOT = {
  id: 'chatbot-1',
  name: "Hunter's Plumbing & Co",
  primary_color: '#f68006',
  widget_position: 'bottom-right',
  welcome_message: "Hi! It's me — how can I help?",
  active: true,
  quick_actions: [{ label: 'Pricing', prompt: 'How much?' }],
}

async function getWidgetJs(overrides: Partial<typeof CHATBOT> = {}) {
  mockSingle.mockResolvedValue({ data: { ...CHATBOT, ...overrides }, error: null })
  const res = await GET(new Request('http://localhost/api/widget/chatbot-1'), {
    params: Promise.resolve({ chatbotId: 'chatbot-1' }),
  })
  return { res, js: await res.text() }
}

describe('GET /api/widget/[chatbotId]', () => {
  it('serves JavaScript', async () => {
    const { res } = await getWidgetJs()
    expect(res.status).toBe(200)
    expect(res.headers.get('Content-Type')).toContain('javascript')
  })

  /**
   * The widget is generated by string interpolation, so a mis-escaped regex
   * produces JS that typecheck and `next build` both accept while every
   * embedding site silently breaks. Compile it here instead.
   */
  it('generates syntactically valid JavaScript', async () => {
    const { js } = await getWidgetJs()
    expect(js.length).toBeGreaterThan(1000)
    expect(() => new Function(js)).not.toThrow()
  })

  it('stays valid when chatbot fields contain quotes and apostrophes', async () => {
    const { js } = await getWidgetJs({
      name: `He said "hi" — O'Brien\\Co`,
      welcome_message: "Don't worry, it's fine \"really\"",
    })
    expect(() => new Function(js)).not.toThrow()
  })

  it('keeps the card regexes intact through template interpolation', async () => {
    const { js } = await getWidgetJs()
    // A lost backslash level turns \w into a literal w and \/ into a bare /
    expect(js).toContain('/^https?:\\/\\//i')
    expect(js).toContain('([\\w.]+)')
  })

  it('returns a comment, not JS, when the chatbot is missing', async () => {
    mockSingle.mockResolvedValue({ data: null, error: { message: 'nope' } })
    const res = await GET(new Request('http://localhost/api/widget/x'), {
      params: Promise.resolve({ chatbotId: 'x' }),
    })
    expect(res.status).toBe(404)
  })
})
